### ISSUE TITLE
valueSetValues for covid-19-lab-test-manufacturer-and-name not found

### ISSUE THREAD

**Issue by astagi** [eu-digital-green-certificates/dcc-quality-assurance#122]
It looks like is not possible to get valueSetValues for covid-19-lab-test-manufacturer-and-name valueset maybe due to a lack of resources. You can see the problem [here](https://dgca-businessrule-service-eu-acc.cfapps.eu10.hana.ondemand.com/valuesets/a64b81660bc718cc42787641a2ed7c6a90002cf631634568fb3104805464942e) (`Possible reasons: The provided hash value is not correct`). 

This problem makes tests failing locally and on PR.

**Comment by libremente** [comment]
@astagi looks like it's solved now https://github.com/eu-digital-green-certificates/dcc-quality-assurance/pull/123#issuecomment-889047717

**Comment by astagi** [comment]
Sounds great @libremente !
