### ISSUE TITLE
IE: Vaccination certificate dosage values contain float values

### ISSUE THREAD

**Issue by confiks** [eu-digital-green-certificates/dcc-quality-assurance#150]
Since the 20th of August, we're getting helpdesk reports that turn out to be float values in the dosage numbers of IE vaccination DCCs. This issue has been reported to the Ireland team on the same day. Since we're getting a lot of reports (also [public](https://twitter.com/DonnellPaddy/status/1430097576704028680)) about this issue, we're moving to allow whole-number float values in our verifier application (so `1.0`, but not `1.5` or `1.0001`).

1) Can this case be reproduced with acceptance keys and added to [SpecialCaseHandling.md](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/main/SpecialCaseHandling.md) so it can be checked by other member states.
2) We're assuming the dosage floats are _always_ whole numbers, i.e. `1.0 / 1.0`, and never something like `1.5 / 1.0` or `1.0001 / 1.0`. Is that right?
3) What is the timeline on getting this fixed on the issuer side?

I only have production examples, which I can't share here, so I've recreated the scenario with the NL signer and NL acceptance keys (`IE` CWT issuer due to details on our side):

```
HC1:NCF%RN%TS3DH0RGPJB/IB-OM7533SR769CIN3XHW2K6R5EJH5.AAVDXGHP80K1JZZPQA37S47*KB*KYQTKWTNS4.$S6ZCJKBHC3KD3ZQT.LJ/9TL4T.B9GYP:S92 A9PPYW5TW5B/94O5JWE9.M2RURV1RU1QK98O92+PHN9F/9BL5CIE/YU1Y9YPDN*I4OIMEDTJCJKDLEDL9CZTAMEIW CI4U/DCYZJ+PB/VSQOL9DLKWCZ3EBKDHOJ7UJQWT.+S1QDC8CC8C$8D7AD9ZI1FV25WRH0CP4Y5LWERLW4G%89-8CNNI:C01HYE97NV8/FVD98-O7I54IJZJJ1W4*$I*NVPC1LJL4A7K73YNSRB7-FHTGL3HHL853IO3NV5W4*LP$V2GHKW/FMKKY0K5$02.AS*7SA065QW-CC4PM0GD:DU7TQ84B8U 5PX$4MRP1722+PYVAHBS/%D:VA%-UL2MSZL/7A$4WRTOPXU+3FGFWB9N3E1IKPO.T7NCWAUZTLRLO:/KK3S65OJYCHIG%KDT-L/Q2$8KY2H7E9R0T000U50VDW1UK%2
```

We've done testing on other verifier apps, with these results:

```
- NL CC: ❌ (invalid QR)
- NL DCC: ❌ (invalid QR)
- BE: ❌ (format not recognized)
- CH: ❌ (format invalid)
- LU: ✅❌ (parses as 1/1, but invalid code IE en invalid code vaccine, maybe config problem)
- IT: ✅
- CZ: ❌ (unable to recognize QR format)
- DK: ✅
- AT: ❌ (Ihr certifikat ist zeitlich abgelaufen / fehler VA3)
- FR: ✅
- HU: ✅
- PT: ✅
- LV: ✅
```

Could countries who accept these QRs with float dosage values indicate how they handle this case? Are you casting, flooring, rounding?

**Comment by confiks** [comment]
I initially posted a specimen acceptance QR code in the opening post; updated it to a non-specimen acceptance QR code now.

**Comment by chrloch** [comment]
Closing with merge of #152
