### ISSUE TITLE
EU DCC iat exp values

### ISSUE THREAD

**Issue by sehaswaran** [eu-digital-green-certificates/dcc-quality-assurance#155]
we scanned an ES country , EU DCC code
we are getting
iat 2021-07-20 07:33:17 and
exp 2021-08-19 07:33:17
for vaccination
is it  an valid values ?
in ES country, EU DCC vaccination is valid for only one month ?

**Comment by chrloch** [comment]
In a hypothetical situation, the date of vaccination could be much earlier than date of issuance: Person has a paper proof of vaccination but only gets a digital certificate one month before they'd have to get their refresh.
