### ISSUE TITLE
QRs that do not conform to the regulation are not labeled

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dcc-quality-assurance#156]
In merge #148 we're merging Qr's that do not meet the Regulation (extra PII, such as passport number and Sex).

May be wise to either mark them thus - or have a separate folder that says 'in-compliant certs for testing'. As to avoid that implementors make a mistaken assumption.

**Comment by chrloch** [comment]
Should we introduce a kind of "Non-EU" tag to indicate that?

**Comment by dirkx** [comment]
We'll - I'd go a step further - and have very separate 'tree's or something; those that Comply. And those that do not. So that it is very obvious what you should test against (or are allowed to test against).

**Comment by mkubicek-dtc** [comment]
@dirkx DCC verifiers should read all DCCs "in the wild". What is the point of marking them as compliant / non-compliant? This repo lists all DCC variations.

**Comment by chrloch** [comment]
Extra fields that do not break the schema are allowed for non-EU countries.
Test does now disallow extra fields for EU countries, as the schema allows them for all.
