### ISSUE TITLE
QRs of SG render badly

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dcc-quality-assurance#157]
There seems to be an aliasing artefact in the SG Qr coes from PR#157:

Enlarged example:

<img width="409" alt="Screenshot 2021-09-03 at 14 21 20" src="https://user-images.githubusercontent.com/392583/132004328-3fbfa38a-4ed7-4aa2-90a5-079eac9f1de3.png">
148.

**Comment by mkubicek-dtc** [comment]
@zawmyolatt FYI
