### ISSUE TITLE
CH: Check 1.0.0 special cases

### ISSUE THREAD

**Issue by mkubicek-dtc** [eu-digital-green-certificates/dcc-quality-assurance#18]
![REC_CH_BAG](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/dea6c4d83df0d77ff5a59311435fde254b168509/CH/1.2.1/specialcases/REC_CH_BAG.png)

![VAC_CH_BAG](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/dea6c4d83df0d77ff5a59311435fde254b168509/CH/1.2.1/specialcases/VAC_CH_BAG.png)

![TEST_CH_BAG](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/dea6c4d83df0d77ff5a59311435fde254b168509/CH/1.2.1/specialcases/TEST_CH_BAG.png)

**Comment by RKlaus-tsi** [comment]
iOS V1.0.4.1: Validator app shows "valid" for all 3 certs
Android V1.0.4-acc Validator app shows "valid" for all 3 certs
