### ISSUE TITLE
CI Script: Strict Schema Validation

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dcc-quality-assurance#20]
The Script should load from a subfolder all Schemas and should check this schema against the QR code and the embedded version number. If the schema is not fullfilled, the codes are returned. E.g. fnt: "Ärmel" --> fails because [A-Z>]$ is allowed

**Comment by chrloch** [comment]
Should be done with https://github.com/eu-digital-green-certificates/dcc-quality-assurance/pull/35
