### ISSUE TITLE
Production vaccination certificates for UY (Uruguay) seem not to have proper format

### ISSUE THREAD

**Issue by hesusruiz** [eu-digital-green-certificates/dcc-quality-assurance#203]
Hi, I don't know if this belongs here but any help would be appreciated.
We have received a complaint from a citizen of Uruguay saying that his certificate is not validated by the official verifier app of the Government of Catalonia.

Uruguay has a valid public key in the Trusted List (kid=**"woowbyJtRFo="**), and the certificate of the citizen is correctly signed by the corresponding private key.
However, the format of the certificate seems incorrect, as instead of the fields "ver" and "dob" and structures "nam" and "v", the certificate has the fields "**Date**", "**Name**", "**CountryCode**", "**DocumentType**", "**DocumentNumber**" an a structure "**VaccinationInfo**".

I tend to think that this is an invalid certificate, but given that it is correctly signed by the private key of Uruguay (as I said, the public key is in the official Trusted List), I wonder if anybody has encountered something similar.

By the way, the test certificate in this repository has the correct format, so it seems a problem related to issuance in production. As additional information, the issuance date of the incorrect certificate is December 28th.

Do you have any reccommendations on this subject?
Thanks in advance,
Jesus Ruiz

**Comment by vanrellmichell** [comment]
Hi,

In Uruguay we have two different QRs:
- Covid passport QR
- The vaccionation certificate QR: This last one is used only for internal purposes.

This person is not using the covid passport QR. He is using the vaccination QR and that is the problem. 

Regards.

**Comment by rschombu** [comment]
closed due to feedback from the issuer country
