### ISSUE TITLE
CI Script: Extended Key Usage

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dcc-quality-assurance#21]
The script should check if the right certificate is used for the OIDs placed in the certificate.

**Comment by mkubicek-dtc** [comment]
@chrloch as reference: Check A.4 in https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf

**Comment by chrloch** [comment]
Document says that "In absence of any key usage extension, this certificate can be used to validate any type of
HCERT. "

However, some certs have extended key usage that does not match the EU values
