### ISSUE TITLE
[GB>SCT] Invalid date format

### ISSUE THREAD

**Issue by ikbendewilliam** [eu-digital-green-certificates/dcc-quality-assurance#274]
During some automated tests, we've discovered an issue with new certificates from Scotland.
@andrewkay18981 you've added new certificates, but these seem to have an invalid date format
GB/1.3.0/TEST_SCT.png has a date '2022-01-31T05:00:00+0' 

According to the ISO specification (https://en.wikipedia.org/wiki/ISO_8601), you need to have 2 numbers behind the +
```
<time>Z
--
<time>±hh:mm
<time>±hhmm
<time>±hh
```
This results in an error thrown in our validation app, causing these certificates to be marked as invalid, even though they may be valid. Can you confirm the production certificates of Scotland don't all contain this invalid format? If so, we'll have to add a workaround on our side and other countries may block these codes accidentally.

**Comment by andrewkay18981** [comment]
Thanks @ikbendewilliam I will follow up on this

**Comment by andrewkay18981** [comment]
I have confirmed that this is the case in production. An update will be released to fix this. In the meantime, do we think it's best that the QR code in question be changed to be a special case? I have an updated version of the QR code with this issue fixed that can be uploaded alongside.

**Comment by ikbendewilliam** [comment]
If you expect us to be able to process this type of date, then you should leave it, but if this will be updated and isn't something we should expect to encounter, then I think it would be better to update the current QR-code 🙂

**Comment by andrewkay18981** [comment]
Example QR codes are updated and issuing in production should be patched. Issue can be closed now.

Thanks

**Comment by ikbendewilliam** [comment]
Thank you for fixing this 👍
