### ISSUE TITLE
SE: VAC gives potentially wrong vaccine name.

### ISSUE THREAD

**Issue by DaveTheBabe** [eu-digital-green-certificates/dcc-quality-assurance#31]
SE: VAC.png gives Astra vaccine name but reports BioNtech as manufacturerer, is this correct?
Name reported: Vaxzevria 

//Swedavia IT

**Comment by chrloch** [comment]
Both codes are represented correctly. The app does not verify wether the manufacturer actually produces the vaccine.

**Comment by chrloch** [comment]
0/VAC.png] {1: 'SE', 4: 1631526603, 6: 1623750603, -260: {1: {'v': [{'ci': 'URN:UVCI:01:SE:EHM/V100000024GI5HM', 'co': 'SE', 'dn': 2, 'dt': '2021-05-18', 'is': 'Swedish eHealth Agency', 'ma': 'ORG-100030215', 'mp': 'EU/1/21/1529', 'sd': 2, 'tg': '840539006', 'vp': 'J07BX03'}], 'dob': '1958-11-11', 'nam': {'fn': 'Lövström', 'gn': 'Oscar', 'fnt': 'LOEVSTROEM', 'gnt': 'OSCAR'}, 'ver': '1.3.0'}}}
Loading HCERT schema 1.3.0 ...
Schema validation passed
