### ISSUE TITLE
BE: REC invalid on iOS but valid on Android

### ISSUE THREAD

**Issue by mkubicek-dtc** [eu-digital-green-certificates/dcc-quality-assurance#5]
As reported by RKlaus-tsi: recovery statement is not valid yet

https://github.com/mkubicek-dtc/dcc-quality-assurance/blob/2d0c3bd3289b7dfc0b4186a22d9d1b1d2c405fd2/BE/1.0.1/REC.png

**Comment by chrloch** [comment]
Retest on 2021-06-24: Works on Android and iOS
