### ISSUE TITLE
DE: REC invalid on iOS but valid on Android

### ISSUE THREAD

**Issue by mkubicek-dtc** [eu-digital-green-certificates/dcc-quality-assurance#6]
Please recheck: https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/0c0461876d3e3b6e92f97e12d06635ef25622359/DE/1.0.0/REC.png

**Comment by mkubicek-dtc** [comment]
`EU Digital Covid Certificate Verifiable QR
{
  "tag": 18,
  "value": [
    { "Map": [ [ 1, -7 ] ] },
    { "Map": [ [ 4, "DEsVUSvpFAE" ] ] },
    {
      "Map": [
        [ 1, "DE" ],
        [ 6, 1622316073 ],
        [ 4, 1643356073 ],
        [
          -260,
          {
            "Map": [
              [
                1,
                {
                  "r": [
                    {
                      "ci": "URN:UVCI:01DE/5CWLU12RNOB9RXSEOP6FG8#W",
                      "is": "Robert Koch-Institut",
                      "co": "DE",
                      "tg": "840539006",
                      "fr": "2021-01-10",
                      "df": "2021-05-29",
                      "du": "2021-06-15"
                    }
                  ],
                  "dob": "1964-08-12",
                  "nam": {
                    "fn": "Mustermann",
                    "gn": "Erika",
                    "fnt": "MUSTERMANN",
                    "gnt": "ERIKA"
                  },
                  "ver": "1.0.0"
                }
              ]
            ]
          }
        ]
      ]
    },
    "Nf3JrTaCVd3ZZTF7LQ2UwmQkeZgVdjAMhZkncC2aB7MXFj7Wn/yHAFxQpdnYUDPVyKchogw+ECW0JcCzcf6yKg=="
  ]
}`

**Comment by RKlaus-tsi** [comment]
Android V1.0.4 Validator shows "valid"
iOS V1.0.4.1 Validator shows "Recovery statement is not valid any more"

**Comment by kerstin-oppermann-tsi** [comment]
Retetst Android V1.0.7 Validator shows "Recovery statement is not valid any more"
fixed
