### ISSUE TITLE
spanish certificates not validating with the android app

### ISSUE THREAD

**Issue by rampa069** [eu-digital-green-certificates/dcc-quality-assurance#60]
Got two spanish certificates, one from the reginal (valencia) authority and another one from the spanish government.

both are giving "failed" in the android app verification.

Decoding manually the CBOR records, in the "valencian" one, can see a difference in the "6" field. In this certificates, they used a decimal point in the expiration date.
{
"1": "ES",
"4": 1685271300,
"6": 1624617519.261,

Also i have a problem verifying the signature:

KeyError: 'Key ID not found in cert list: 65c7e496812f7c64'

decoding the "spanish" one, the timestamp is OK, but i get an error: 

Key ID not found in cert list: a85345d9d0be9a34

may be there is some problem with the signing keys in the gateway?  If you need the png or pdf, let me know how to send it to you.

PS. Related issues are in:

eu-digital-green-certificates/dgca-verifier-app-android#94

and
eu-digital-green-certificates/dgca-verifier-app-android#116

**Comment by kerstin-oppermann-tsi** [comment]
@rampa069  Please can you send us a QR Code so we can reproduce and check. All test codes for spain in the repo are working at the moment with the Android- and iOS-App. Which version of app you are using?

**Comment by rampa069** [comment]
Thanks for replying.

i am using the android 1.1.1 release.
Here is the "valencian" certificate.

![Screenshot_20210625_192935](https://user-images.githubusercontent.com/955226/123755307-0d171580-d8bc-11eb-9771-b7ad77f1cd32.png)

and here the "national" certificate:
![rampa-espana](https://user-images.githubusercontent.com/955226/123755434-2e780180-d8bc-11eb-97a5-f852d9a70233.png)

**Comment by chrloch** [comment]
If the key is not on the gateway, then the behavior is correct.
