### ISSUE TITLE
Austrian certificates not validating in android App

### ISSUE THREAD

**Issue by wiggisser** [eu-digital-green-certificates/dcc-quality-assurance#62]
As asked to by @kerstin-oppermann-tsi  in [this issue](https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/108) I will also create an issue here (for details see other issue). Here just a short sum up:

Test- and vaccination certificates issued by the austrian government cannot be validated in the android app because of a signature error. Ie, the necessary information (name, test- or vaccination date, ...) can be sucessfully extracted from the QR Code. But when trying to validate the signature, no certificate is found for the keyid, thus the test- or vaccination certificate is flagged as invalid.

The signature of both certificates can be validated in the offical webapp of the austrian government "https://qr.gv.at" using the following certificate 

```
-----BEGIN CERTIFICATE-----
MIIB7zCCAZagAwIBAgIKAXnM+L47fmBcezAKBggqhkjOPQQDAjBEMQswCQYDVQQG
EwJBVDEPMA0GA1UECgwGQk1TR1BLMQwwCgYDVQQFEwMwMDExFjAUBgNVBAMMDUFU
IERHQyBDU0NBIDEwHhcNMjEwNjAyMTM0NTI0WhcNMjMwNjAyMTM0NTI0WjBGMQsw
CQYDVQQGEwJBVDEPMA0GA1UECgwGQk1TR1BLMQ8wDQYDVQQFEwYwMDEwMDExFTAT
BgNVBAMMDEFUIERHQyBEU0MgMTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGBN
uKiCpnXH0VlIdk6pJZH2ep8jQaV+FR3izMXxZfK5EPGZLtG3Jx+TmV3JJErfrSrP
hRmfbSidVbTQ5nnZS+ujbjBsMA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4EFgQUNs2s
mrjBhuR5Bqxl6teE1x1o2ycwHwYDVR0jBBgwFoAUHyKsHGUWKbTBmLNjb7/dCZ27
e3swGgYDVR0QBBMwEYEPMjAyMTEyMTYxNDQ1MjRaMAoGCCqGSM49BAMCA0cAMEQC
IDjXHnyzq3sTisMX1uY8xQ2ZqCRL2xmxtYOPhSZ9ZacYAiAqHUMOC7WNgq4h28n3
1WLc1mMPAYauWslSEwnXC79AGw==
-----END CERTIFICATE-----
```

**Comment by chrloch** [comment]
The DSC keys used in the context of this repo are only for the acceptance environment. 
No production keys shall be used here.
