### ISSUE TITLE
UK Pass not verified

### ISSUE THREAD

**Issue by martinbrook** [eu-digital-green-certificates/dcc-quality-assurance#64]
Attaching pass and a link to public keys

[Coronavirus (COVID-19) records.pdf](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/files/6732939/Coronavirus.COVID-19.records.pdf)

https://covid-status.service.nhsx.nhs.uk/pubkeys/keys.json

**Comment by chrloch** [comment]
The data encoded by the QR code must start with the magic number 'HC1:' in order to be a EU compatible DCC. The attached QR code does not.
