### ISSUE TITLE
Feature request: ValueSet validation

### ISSUE THREAD

**Issue by jvitrifork** [eu-digital-green-certificates/dcc-quality-assurance#68]
Consider making the python scripts (https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/main/.github/workflows/dgc-testdata-verification.yml) validate the codes so that no QR codes are uploaded unless their they codes adhere to the defined valuesets.

**Comment by SchulzeStTSI** [comment]
@chrloch Can you please integrate the business rule service for valuesets when it's deployed on BTP? (should be available already)

**Comment by chrloch** [comment]
Implemented in #94 

Merge decision tbd because already approved QR codes are affected
