### ISSUE TITLE
HR: REC invalid on iOS but valid on Android

### ISSUE THREAD

**Issue by mkubicek-dtc** [eu-digital-green-certificates/dcc-quality-assurance#7]
Please recheck: https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/2d0c3bd3289b7dfc0b4186a22d9d1b1d2c405fd2/HR/1.0.0/REC.png

**Comment by mkubicek-dtc** [comment]
@RKlaus-tsi still ambiguous behaviour?

**Comment by RKlaus-tsi** [comment]
@Hendrik-Schmidt-Schierhorn-TSI 
![IMG_20210624_081154](https://user-images.githubusercontent.com/72432210/123211685-140ce500-d4c4-11eb-8f08-d2039e1d81c7.jpg)
iOS schows invalid because "valid until" is in the past
it seems Adroid does not check this attribute because it shows valid

**Comment by kerstin-oppermann-tsi** [comment]
retested with Android 1.0.7 - acc : is fixed
