### ISSUE TITLE
LV: REC invalid on iOS but valid on Android

### ISSUE THREAD

**Issue by mkubicek-dtc** [eu-digital-green-certificates/dcc-quality-assurance#8]
Please recheck: https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/87d74dde4692c803142d600165ff60ca3e243ac8/LV/1.0.0/REC.png

**Comment by ltranvan** [comment]
tvt; check with Android VerifierApp 1.0.4: Typ REC and valid!

**Comment by kerstin-oppermann-tsi** [comment]
Android 1.0.7-acc retest: issue is fixed
