### ISSUE TITLE
Bulgarian certificates verification problem

### ISSUE THREAD

**Issue by mboduroff** [eu-digital-green-certificates/dcc-quality-assurance#96]
Bulgarian vaccination certificate cannot be verified using app (Android 'tst' and 'acc' releases, tested using all versions up to 1.1.5). Recently (July 4) all certificates of vaccination issued by the Bulgarian government to those vaccinated with the Pfizer/BioNTech and the Moderna vaccines were reissued, apparently due to a mistake in the 'Manufacturer' field in both vaccines. Still, neither my old certificate, nor my new one, are read correctly by the app - I get the "Verification invalid" message.

**Comment by daniel-eder** [comment]
The apps "tst" and "acc" are builds for the test and acceptance environment respectively, they do not work on the production environment.

EU Member states have sovereignty over apps in the production environment - if you use one of the official app builds (that are connected to a national backend in the production environment) the certificates will be valid. If certificates are not valid on an official app, please reopen this issue with the updated information.
